/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author MSI
 */
public class GestionDeOrden extends javax.swing.JFrame {

    /**
     * Creates new form GestionDeOrden
     */
    public GestionDeOrden() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTituloOrden = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        labelPrecioTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMenu = new javax.swing.JTable();
        labelTituloMenu = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaOrdenProductos = new javax.swing.JTable();
        buttonAgregarProducto = new javax.swing.JButton();
        buttonEliminarProducto = new javax.swing.JButton();
        buttonTerminarOrden = new javax.swing.JButton();
        buttonCancelarPanel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTituloOrden.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        labelTituloOrden.setText("Gestión de Órden [idOrden] ");

        labelCliente.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelCliente.setText("Cliente: [cliente]");

        labelPrecioTotal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelPrecioTotal.setText("Total: [precioTotal]");

        tablaMenu.setBackground(new java.awt.Color(213, 250, 194));
        tablaMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Categoria", "Precio (S/.)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaMenu);
        if (tablaMenu.getColumnModel().getColumnCount() > 0) {
            tablaMenu.getColumnModel().getColumn(0).setResizable(false);
            tablaMenu.getColumnModel().getColumn(0).setPreferredWidth(25);
            tablaMenu.getColumnModel().getColumn(1).setResizable(false);
            tablaMenu.getColumnModel().getColumn(1).setPreferredWidth(200);
            tablaMenu.getColumnModel().getColumn(2).setResizable(false);
            tablaMenu.getColumnModel().getColumn(2).setPreferredWidth(75);
            tablaMenu.getColumnModel().getColumn(3).setResizable(false);
            tablaMenu.getColumnModel().getColumn(3).setPreferredWidth(35);
        }

        labelTituloMenu.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        labelTituloMenu.setText("Menú de los platos");
        labelTituloMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        tablaOrdenProductos.setBackground(new java.awt.Color(213, 250, 194));
        tablaOrdenProductos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tablaOrdenProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Categoria", "Precio (S/.)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaOrdenProductos);
        if (tablaOrdenProductos.getColumnModel().getColumnCount() > 0) {
            tablaOrdenProductos.getColumnModel().getColumn(0).setResizable(false);
            tablaOrdenProductos.getColumnModel().getColumn(0).setPreferredWidth(25);
            tablaOrdenProductos.getColumnModel().getColumn(1).setResizable(false);
            tablaOrdenProductos.getColumnModel().getColumn(1).setPreferredWidth(200);
            tablaOrdenProductos.getColumnModel().getColumn(2).setResizable(false);
            tablaOrdenProductos.getColumnModel().getColumn(2).setPreferredWidth(75);
            tablaOrdenProductos.getColumnModel().getColumn(3).setResizable(false);
            tablaOrdenProductos.getColumnModel().getColumn(3).setPreferredWidth(35);
        }

        buttonAgregarProducto.setBackground(new java.awt.Color(34, 141, 110));
        buttonAgregarProducto.setForeground(new java.awt.Color(255, 255, 255));
        buttonAgregarProducto.setText("Agregar selección a la Orden");
        buttonAgregarProducto.setMargin(new java.awt.Insets(2, 2, 2, 2));
        buttonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarProductoActionPerformed(evt);
            }
        });

        buttonEliminarProducto.setBackground(new java.awt.Color(34, 141, 110));
        buttonEliminarProducto.setForeground(new java.awt.Color(255, 255, 255));
        buttonEliminarProducto.setText("Eliminar de la Orden");
        buttonEliminarProducto.setMargin(new java.awt.Insets(2, 2, 2, 2));
        buttonEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarProductoActionPerformed(evt);
            }
        });

        buttonTerminarOrden.setBackground(new java.awt.Color(34, 141, 110));
        buttonTerminarOrden.setForeground(new java.awt.Color(255, 255, 255));
        buttonTerminarOrden.setText("Terminar Orden");
        buttonTerminarOrden.setMargin(new java.awt.Insets(2, 2, 3, 2));

        buttonCancelarPanel.setBackground(new java.awt.Color(34, 141, 110));
        buttonCancelarPanel.setForeground(new java.awt.Color(255, 255, 255));
        buttonCancelarPanel.setText("Cancelar");
        buttonCancelarPanel.setMargin(new java.awt.Insets(2, 2, 2, 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelPrecioTotal)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                                .addComponent(buttonTerminarOrden, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonEliminarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonCancelarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(labelTituloOrden)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                            .addComponent(buttonAgregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTituloMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(labelTituloMenu)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTituloOrden)
                    .addComponent(buttonCancelarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCliente)
                    .addComponent(labelPrecioTotal))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonTerminarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAgregarProductoActionPerformed

    private void buttonEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEliminarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDeOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDeOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDeOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDeOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionDeOrden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buttonAgregarProducto;
    public javax.swing.JButton buttonCancelarPanel;
    public javax.swing.JButton buttonEliminarProducto;
    public javax.swing.JButton buttonTerminarOrden;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JLabel labelCliente;
    public javax.swing.JLabel labelPrecioTotal;
    private javax.swing.JLabel labelTituloMenu;
    public javax.swing.JLabel labelTituloOrden;
    public javax.swing.JTable tablaMenu;
    public javax.swing.JTable tablaOrdenProductos;
    // End of variables declaration//GEN-END:variables
}
