/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author josep
 */
public class GestionDePagos extends javax.swing.JFrame {

    /**
     * Creates new form GestiónDePagos
     */
    public GestionDePagos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        labelCliente = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldMonto = new javax.swing.JTextField();
        labelTotal = new javax.swing.JLabel();
        labeldOrden = new javax.swing.JLabel();
        labelTituloForm = new javax.swing.JLabel();
        buttonProcesarPago = new javax.swing.JButton();
        buttonGenerarRecibo = new javax.swing.JButton();
        buttonCancelarPago = new javax.swing.JButton();
        comboboxMetodos = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(425, 224));
        setMinimumSize(new java.awt.Dimension(425, 224));
        setSize(new java.awt.Dimension(425, 224));

        labelCliente.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelCliente.setText("[labelNombreCliente]");

        labelFecha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelFecha.setText("[labelFecha-Hora]");
        labelFecha.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Monto:");

        fieldMonto.setBackground(new java.awt.Color(59, 73, 69));
        fieldMonto.setForeground(new java.awt.Color(255, 255, 255));
        fieldMonto.setText("fieldMonto");

        labelTotal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelTotal.setText("Total a Pagar:");

        labeldOrden.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labeldOrden.setText("ID de Orden:");

        labelTituloForm.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        labelTituloForm.setText("Gestión de pago");

        buttonProcesarPago.setBackground(new java.awt.Color(34, 141, 110));
        buttonProcesarPago.setForeground(new java.awt.Color(255, 255, 255));
        buttonProcesarPago.setText("Procesar pago");
        buttonProcesarPago.setMaximumSize(new java.awt.Dimension(100, 25));
        buttonProcesarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProcesarPagoActionPerformed(evt);
            }
        });

        buttonGenerarRecibo.setBackground(new java.awt.Color(34, 141, 110));
        buttonGenerarRecibo.setForeground(new java.awt.Color(255, 255, 255));
        buttonGenerarRecibo.setText("GenerarRecibo");
        buttonGenerarRecibo.setMaximumSize(new java.awt.Dimension(100, 25));
        buttonGenerarRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenerarReciboActionPerformed(evt);
            }
        });

        buttonCancelarPago.setBackground(new java.awt.Color(34, 141, 110));
        buttonCancelarPago.setForeground(new java.awt.Color(255, 255, 255));
        buttonCancelarPago.setText("Cancelar Pago");
        buttonCancelarPago.setMaximumSize(new java.awt.Dimension(100, 25));
        buttonCancelarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarPagoActionPerformed(evt);
            }
        });

        comboboxMetodos.setBackground(new java.awt.Color(59, 73, 69));
        comboboxMetodos.setForeground(new java.awt.Color(255, 255, 255));
        comboboxMetodos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta" }));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Método");

        jTextField1.setBackground(new java.awt.Color(59, 73, 69));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("fieldIDOrden");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelFecha)
                        .addGap(106, 106, 106))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(buttonProcesarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonGenerarRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fieldMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonCancelarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboboxMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTotal)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(220, 220, 220)
                                        .addComponent(labeldOrden)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 90, Short.MAX_VALUE))))
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(labelTituloForm)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(labelTituloForm)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCliente)
                    .addComponent(labelFecha))
                .addGap(22, 22, 22)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(comboboxMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonProcesarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonGenerarRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCancelarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTotal)
                            .addComponent(labeldOrden)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonProcesarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcesarPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonProcesarPagoActionPerformed

    private void buttonGenerarReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenerarReciboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGenerarReciboActionPerformed

    private void buttonCancelarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelarPagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDePagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDePagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDePagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDePagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionDePagos().setVisible(true);
            }
        });
    }

    public JButton getButtonCancelarPago() {
        return buttonCancelarPago;
    }

    public JButton getButtonGenerarRecibo() {
        return buttonGenerarRecibo;
    }

    public JButton getButtonProcesarPago() {
        return buttonProcesarPago;
    }

    public JTextField getFieldMonto() {
        return fieldMonto;
    }

    public JLabel getLabelCliente() {
        return labelCliente;
    }

    public JLabel getLabelFecha() {
        return labelFecha;
    }

    public JLabel getLabelTituloForm() {
        return labelTituloForm;
    }

    public JLabel getLabelTotal() {
        return labelTotal;
    }

    public JLabel getLabeldOrden() {
        return labeldOrden;
    }

    public JComboBox<String> getComboboxMetodos() {
        return comboboxMetodos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelarPago;
    private javax.swing.JButton buttonGenerarRecibo;
    private javax.swing.JButton buttonProcesarPago;
    private javax.swing.JComboBox<String> comboboxMetodos;
    private javax.swing.JTextField fieldMonto;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelTituloForm;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labeldOrden;
    // End of variables declaration//GEN-END:variables
}
