/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author josep
 */
public class GestionDeOrdenes extends javax.swing.JFrame {
    
    /**
     * Creates new form GestiónDeOrdenes
     */
    public GestionDeOrdenes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        framePago = new javax.swing.JFrame();
        labelTituloForm = new javax.swing.JLabel();
        labelRol = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        buttonVolverPanel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaOrdenes = new javax.swing.JTable();
        buttonAgregarOrden = new javax.swing.JButton();
        labelNombreUsuario = new javax.swing.JLabel();
        labelIdUsuario = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        fieldCliente = new javax.swing.JTextField();
        labelTituloFecha2 = new javax.swing.JLabel();

        javax.swing.GroupLayout framePagoLayout = new javax.swing.GroupLayout(framePago.getContentPane());
        framePago.getContentPane().setLayout(framePagoLayout);
        framePagoLayout.setHorizontalGroup(
            framePagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        framePagoLayout.setVerticalGroup(
            framePagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(552, 547));
        setSize(new java.awt.Dimension(552, 547));

        labelTituloForm.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        labelTituloForm.setText("Gestión de órdenes");

        labelRol.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelRol.setText("Rol:");
        labelRol.setToolTipText("");

        labelFecha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelFecha.setText("Fecha: ");

        buttonVolverPanel.setText("Volver");

        tablaOrdenes.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tablaOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Estado", "Precio total (S/.)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaOrdenes);
        if (tablaOrdenes.getColumnModel().getColumnCount() > 0) {
            tablaOrdenes.getColumnModel().getColumn(0).setMinWidth(50);
            tablaOrdenes.getColumnModel().getColumn(0).setPreferredWidth(50);
            tablaOrdenes.getColumnModel().getColumn(0).setMaxWidth(50);
            tablaOrdenes.getColumnModel().getColumn(1).setMinWidth(175);
            tablaOrdenes.getColumnModel().getColumn(1).setPreferredWidth(175);
            tablaOrdenes.getColumnModel().getColumn(1).setMaxWidth(175);
            tablaOrdenes.getColumnModel().getColumn(2).setMinWidth(100);
            tablaOrdenes.getColumnModel().getColumn(2).setPreferredWidth(100);
            tablaOrdenes.getColumnModel().getColumn(2).setMaxWidth(100);
            tablaOrdenes.getColumnModel().getColumn(3).setMinWidth(125);
            tablaOrdenes.getColumnModel().getColumn(3).setPreferredWidth(125);
            tablaOrdenes.getColumnModel().getColumn(3).setMaxWidth(125);
        }

        buttonAgregarOrden.setText("Agregar Orden");
        buttonAgregarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarOrdenActionPerformed(evt);
            }
        });

        labelNombreUsuario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNombreUsuario.setText("Nombre Usuario:");

        labelIdUsuario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelIdUsuario.setText("ID Usuario:");

        labelCliente.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelCliente.setText("Cliente:");

        fieldCliente.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        fieldCliente.setToolTipText("");
        fieldCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldClienteActionPerformed(evt);
            }
        });

        labelTituloFecha2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(buttonVolverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(labelTituloForm))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(200, 200, 200)
                                    .addComponent(buttonAgregarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(130, 130, 130)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRol)
                            .addComponent(labelNombreUsuario)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFecha)
                            .addComponent(labelIdUsuario)
                            .addComponent(labelTituloFecha2))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTituloForm)
                    .addComponent(buttonVolverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelRol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelNombreUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelIdUsuario)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCliente)
                        .addComponent(fieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelTituloFecha2))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(buttonAgregarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldClienteActionPerformed

    private void buttonAgregarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAgregarOrdenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDeOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDeOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDeOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDeOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionDeOrdenes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buttonAgregarOrden;
    public javax.swing.JButton buttonVolverPanel;
    public javax.swing.JTextField fieldCliente;
    private javax.swing.JFrame framePago;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCliente;
    public javax.swing.JLabel labelFecha;
    public javax.swing.JLabel labelIdUsuario;
    public javax.swing.JLabel labelNombreUsuario;
    public javax.swing.JLabel labelRol;
    private javax.swing.JLabel labelTituloFecha2;
    private javax.swing.JLabel labelTituloForm;
    public javax.swing.JTable tablaOrdenes;
    // End of variables declaration//GEN-END:variables

}
