/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.*;

/**
 *
 * @author josep
 */

public class PanelPrincipal extends javax.swing.JFrame {
    
    public PanelPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelNombreUsuario = new javax.swing.JLabel();
        labelRol = new javax.swing.JLabel();
        buttonCerrarSesion = new javax.swing.JButton();
        buttonGestionarOrdenes = new javax.swing.JButton();
        buttonGestionarVentas = new javax.swing.JButton();
        buttonGestionarCajeros = new javax.swing.JButton();
        labelFecha = new javax.swing.JLabel();
        labelIdUsuario = new javax.swing.JLabel();
        buttonGestionarMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_algo2_proyecto.png")));// NOI18N

        labelNombreUsuario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNombreUsuario.setText("[Usuario: NombreUsuario]");

        labelRol.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelRol.setText("[Rol: Administrador]");

        buttonCerrarSesion.setBackground(new java.awt.Color(34, 141, 110));
        buttonCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        buttonCerrarSesion.setText("Cerrar sesión");
        buttonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCerrarSesionActionPerformed(evt);
            }
        });

        buttonGestionarOrdenes.setBackground(new java.awt.Color(34, 141, 110));
        buttonGestionarOrdenes.setForeground(new java.awt.Color(255, 255, 255));
        buttonGestionarOrdenes.setText("Gestión de órdenes");
        buttonGestionarOrdenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGestionarOrdenesActionPerformed(evt);
            }
        });

        buttonGestionarVentas.setBackground(new java.awt.Color(34, 141, 110));
        buttonGestionarVentas.setForeground(new java.awt.Color(255, 255, 255));
        buttonGestionarVentas.setText("Registro de ventas");
        buttonGestionarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGestionarVentasActionPerformed(evt);
            }
        });

        buttonGestionarCajeros.setBackground(new java.awt.Color(34, 141, 110));
        buttonGestionarCajeros.setForeground(new java.awt.Color(255, 255, 255));
        buttonGestionarCajeros.setText("Gestión de cajeros");
        buttonGestionarCajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGestionarCajerosActionPerformed(evt);
            }
        });

        labelFecha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelFecha.setText("[Fecha]");

        labelIdUsuario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelIdUsuario.setText("[ID]");

        buttonGestionarMenu.setBackground(new java.awt.Color(34, 141, 110));
        buttonGestionarMenu.setForeground(new java.awt.Color(255, 255, 255));
        buttonGestionarMenu.setText("Gestión del menú");
        buttonGestionarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGestionarMenuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setText("Dashboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRol)
                    .addComponent(labelNombreUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIdUsuario)
                    .addComponent(labelFecha))
                .addGap(119, 119, 119))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonGestionarCajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel2))
                            .addComponent(buttonGestionarOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonGestionarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonGestionarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(199, 199, 199))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRol)
                    .addComponent(labelFecha))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreUsuario)
                    .addComponent(labelIdUsuario))
                .addGap(25, 25, 25)
                .addComponent(buttonGestionarOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonGestionarCajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonGestionarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonGestionarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCerrarSesionActionPerformed

    private void buttonGestionarOrdenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGestionarOrdenesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGestionarOrdenesActionPerformed

    private void buttonGestionarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGestionarVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGestionarVentasActionPerformed

    private void buttonGestionarCajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGestionarCajerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGestionarCajerosActionPerformed

    private void buttonGestionarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGestionarMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGestionarMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrincipal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buttonCerrarSesion;
    public javax.swing.JButton buttonGestionarCajeros;
    public javax.swing.JButton buttonGestionarMenu;
    public javax.swing.JButton buttonGestionarOrdenes;
    public javax.swing.JButton buttonGestionarVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel labelFecha;
    public javax.swing.JLabel labelIdUsuario;
    public javax.swing.JLabel labelNombreUsuario;
    public javax.swing.JLabel labelRol;
    // End of variables declaration//GEN-END:variables
}
